Update HsCommandInterpreter.cc
overloads call to make_shared require std
compile  error prior change


/root/tmpBuilds/hypertable/src/cc/Hyperspace/HsCommandInterpreter.cc: In member function virtual int Hyperspace::HsCommandInterpreter::execute_line(const String&):
/root/tmpBuilds/hypertable/src/cc/Hyperspace/HsCommandInterpreter.cc:96:78: error: call of overloaded make_shared<Hyperspace::FileHandleCallback>(int&) is ambiguous
       HandleCallbackPtr callback = make_shared<FileHandleCallback>(event_mask);
                                                                              ^
In file included from /usr/local/include/c++/7.1.0/memory:81:0,
                 from /root/tmpBuilds/hypertable/src/cc/Common/Compat.h:39,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/HsCommandInterpreter.cc:22:
/usr/local/include/c++/7.1.0/bits/shared_ptr.h:703:5: note: candidate: std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = Hyperspace::FileHandleCallback; _Args = {int&}]
     make_shared(_Args&&... __args)
     ^~~~~~~~~~~
In file included from /usr/local/include/boost/smart_ptr/make_shared.hpp:15:0,
                 from /usr/local/include/boost/thread/future.hpp:60,
                 from /usr/local/include/boost/thread.hpp:24,
                 from /root/tmpBuilds/hypertable/src/cc/Common/Thread.h:28,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/BerkeleyDbFilesystem.h:44,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/Event.h:28,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/Notification.h:25,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/Protocol.h:38,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/HsParser.h:33,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/HsCommandInterpreter.cc:26:
/usr/local/include/boost/smart_ptr/make_shared_object.hpp:248:87: note: candidate: typename boost::detail::sp_if_not_array<T>::type boost::make_shared(Args&& ...) [with T = Hyperspace::FileHandleCallback; Args = {int&}; typename boost::detail::sp_if_not_array<T>::type = boost::shared_ptr<Hyperspace::FileHandleCallback>]
 template< class T, class... Args > typename boost::detail::sp_if_not_array< T >::type make_shared( Args && ... args )
                                                                                       ^~~~~~~~~~~
/root/tmpBuilds/hypertable/src/cc/Hyperspace/HsCommandInterpreter.cc:118:78: error: call of overloaded make_shared<Hyperspace::FileHandleCallback>(int&) is ambiguous
       HandleCallbackPtr callback = make_shared<FileHandleCallback>(event_mask);
                                                                              ^
In file included from /usr/local/include/c++/7.1.0/memory:81:0,
                 from /root/tmpBuilds/hypertable/src/cc/Common/Compat.h:39,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/HsCommandInterpreter.cc:22:
/usr/local/include/c++/7.1.0/bits/shared_ptr.h:703:5: note: candidate: std::shared_ptr<_Tp> std::make_shared(_Args&& ...) [with _Tp = Hyperspace::FileHandleCallback; _Args = {int&}]
     make_shared(_Args&&... __args)
     ^~~~~~~~~~~
In file included from /usr/local/include/boost/smart_ptr/make_shared.hpp:15:0,
                 from /usr/local/include/boost/thread/future.hpp:60,
                 from /usr/local/include/boost/thread.hpp:24,
                 from /root/tmpBuilds/hypertable/src/cc/Common/Thread.h:28,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/BerkeleyDbFilesystem.h:44,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/Event.h:28,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/Notification.h:25,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/Protocol.h:38,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/HsParser.h:33,
                 from /root/tmpBuilds/hypertable/src/cc/Hyperspace/HsCommandInterpreter.cc:26:
/usr/local/include/boost/smart_ptr/make_shared_object.hpp:248:87: note: candidate: typename boost::detail::sp_if_not_array<T>::type boost::make_shared(Args&& ...) [with T = Hyperspace::FileHandleCallback; Args = {int&}; typename boost::detail::sp_if_not_array<T>::type = boost::shared_ptr<Hyperspace::FileHandleCallback>]
 template< class T, class... Args > typename boost::detail::sp_if_not_array< T >::type make_shared( Args && ... args )
                                                                                       ^~~~~~~~~~~
make[2]: *** [src/cc/Hyperspace/CMakeFiles/Hyperspace.dir/build.make:255: src/cc/Hyperspace/CMakeFiles/Hyperspace.dir/HsCommandInterpreter.cc.o] Error 1